### PR TITLE
Made sure image data wasn't being written into memory

### PR DESCRIPTION
**Pull request by betaredex**

### CODE REVIEW

**Comment by rudolphpienaar** [comment]
Hey @betaredex  -- I posted the diffs to the slack #general channel but can add here too...

[pfioh.txt](https://github.com/FNNDSC/pfioh/files/3064827/pfioh.txt)
[pman.txt](https://github.com/FNNDSC/pfioh/files/3064828/pman.txt)

**Comment by danmcp** [comment]
@jbernal0019 Any help you can provide about the error we are seeing in Travis for this pull?

```
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1091, "Can't DROP 'end_date'; check that column/key exists")
```

**Comment by rudolphpienaar** [comment]
hey @danmcp @betaredex  -- Had the same issue with `pfcon`. 

In the `cube_before_script.sh`, remove the line

```docker-compose exec chris_dev python manage.py migrate```

According to @jbernal, migrations for CUBE are now applied as part of the CUBE’s entrypoint. So no need to apply them in the **make** or Travis file.

Please fix and if the tests work I'll do my local test after.

**Comment by danmcp** [comment]
@betaredex Want to make that change in your pull in a separate commit?

**Comment by jbernal** [comment]
Hi all -

I believe you have the wrong recipient for this thread.


---------------------
José Bernal
Web/Application Engineer
Cell 541-228-8481
jbernal.web.dev@gmail.com

**Comment by jbernal0019** [comment]
Guys FYI I'm @jbernal0019 :)

**Comment by rudolphpienaar** [comment]
@betaredex @danmcp  -- I want to clone your fork and build a local system. @betaredex  -- what branch of your fork should I clone locally?

**Comment by danmcp** [comment]
@rudolphpienaar It looks like it's the bugfix branch

**Comment by rudolphpienaar** [comment]
Ok -- and similarly for `pman` I'm assuming...

**Comment by danmcp** [comment]
Yeah it looks like it.  Note that you can see it at the top of this page under the title.

**Comment by rudolphpienaar** [comment]
Yep -- I actually just saw that, too!

**Comment by rudolphpienaar** [comment]
@danmcp @betaredex --

Full integration tests are failing. I built local containers of Elliot's fork/branch as well as local containers of CUBE, ChRIS_store, and pfcon.

The errors seem clustered around `mount_dir.py` and calling parameters from `pfioh.py`. I'll see about attaching a git diff to this thread.

I have fixed some errors.. the `putData` and related seem to be working. However, right now it seems that the `getData` method fails. This might require more debugging.

I am out of office tomorrow and Friday. Will keep digging when/if I have time.

**Comment by rudolphpienaar** [comment]
[git-diff.txt](https://github.com/FNNDSC/pfioh/files/3184603/git-diff.txt)

**Comment by betaredex** [comment]
@rudolphpienaar That was because I tried to change some of the paths to make it more consistent between swift_store/mount_dir and between zip/non-zip. Can you send me the error logs?
I removed ```d[write][file] = fileName``` because fileName is never sent (and there's no guarantee that the output would be a file rather than a directory anyway)

**Comment by rudolphpienaar** [comment]
Yeah, well those changes, logical as they may be, broke the integration tests. The put is working. The get is failing for probably generally similar reasons.

I'll see about getting error logs (the put case was simple python errors).

**Comment by rudolphpienaar** [comment]
Ok -- I've done some pretty extensive debugging and testing and it looks all good to me now.

Attached are the git diffs since I don't think I can fork your fork and do a PR. That just seems super convoluted.

[pfioh-diff.txt](https://github.com/FNNDSC/pfioh/files/3218350/pfioh-diff.txt)
[pman-diff.txt](https://github.com/FNNDSC/pfioh/files/3218351/pman-diff.txt)

**Comment by rudolphpienaar** [comment]
The issues were relatively minor -- just some API mismatching and small things.

What took literally days of debugging was eventually tracked down to a test within the `pfurl` that was embedded within `pfcon`. Essentially the return zip from one of the integration tests was smaller than a hardwired length threshold, which was a very simple (and very dumb) test for pull failure (if the pulled zip was less than say 800 bytes there was a good chance something went wrong). Problem was that for some reason that I never explored fully the pull payload in one of the tests was smaller than that, but still valid.

**Comment by rudolphpienaar** [comment]
I also built the summit tree again using my modified `pfioh` and `pman` to make sure it was in fact working and all worked.

One note I'll make here so that it is recorded is that it seems that multiple in parallel calls to CUBE might break things. For instance if you have a tree branch and calling the plugin on each branch in parallel (and not in series) seemed to break. 

I haven't explored fully, but this might be an issue.

**Comment by betaredex** [comment]
@rudolphpienaar I believe I fixed the problem.

**Comment by rudolphpienaar** [comment]
Can you please apply all the diffs, esp as regards the changes to `pfioh`, `setup.py`, `README.rst` etc otherwise I'll have to do all that again before I approve. Mostly this was some legibility, some typos, and the internal versioning which is very useful esp for pushing up to PyPI.

Similarly for `pman`.

**Comment by rudolphpienaar** [comment]
Integration tests are still failing when I test on local images.

@betaredex -- did you actually run CUBE via the page about debugging containerized services off your local builds? For a start, there was a minor typo on pfioh/bin/pfioh that makes me think you might not have run the whole system from CUBE.

**Comment by rudolphpienaar** [comment]
diff --git a/bin/pfioh b/bin/pfioh
index 359867a..d3f9875 100755
--- a/bin/pfioh
+++ b/bin/pfioh
@@ -258,7 +258,7 @@ parser.add_argument(
     '--enableTokenAuth',
     action  = 'store_true',
     help    = """Enables token based authorization and can be configured to look for a .ini file
-    or an openshift secret"""
+    or an openshift secret""",
     dest    = 'b_tokenAuth',
     default = False
 )

**Comment by rudolphpienaar** [comment]
(basically there is a missing comma at the end of the ``help`` string for that parameter).

**Comment by betaredex** [comment]
I think that's because I manually copied some of your changes over, and I
didn't test those (since it was all help/versioning stuff)

**Comment by rudolphpienaar** [comment]
I don't think those help / versioning deltas are the issue. Unfortunately, the machine I took with the conference  is not the best choice for dev. Can you test yourself? I still have the mods I made on a different machine @BCH. I could just zip up those dirs and send to you so you can make doubly sure about any deltas.

**Comment by betaredex** [comment]
I can work on it tomorrow but I'm not at the office today.

**Comment by rudolphpienaar** [comment]
np. I'll see if I can confirm that the code on the machine @bch is still working and then see about how to get you those.

**Comment by rudolphpienaar** [comment]
[bugfix.zip](https://github.com/FNNDSC/pfioh/files/3285453/bugfix.zip)

**Comment by rudolphpienaar** [comment]
@betaredex @danmcp 

See above for a zip of my "fixes" to pman/pfioh that actually pass integration tests on my test machine.

**Comment by betaredex** [comment]
Those are failing the tests on my end, so I have no idea what is going on.

**Comment by betaredex** [comment]
That's what I'm doing.

**Comment by rudolphpienaar** [comment]
Ok cool.

I guess worst case I could just effectively use your branch changes over my
personal fork and then PR my fork.

**Comment by rudolphpienaar** [comment]
I'll also test those zips on some more machines.

**Comment by betaredex** [comment]
I manually copied some of the changes from your version. Do you know exactly why my version is failing?
The only major code difference seemed to be not passing fileName to storeData but that shouldn't matter.

**Pull request merged**
