### PR TITLE
Enable swift backend

### PR DESCRIPTION
**Pull request by awalkaradi95moc**
@danmcp @rudolphpienaar Works with mount dir based pfioh and swarm (containerized) pman. It should work with swift but not tested to be 100% sure.

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
@awalkaradi95moc Can you please rebase this PR? @danmcp This is needs review.

**Comment by danmcp** [comment]
@awalkaradi95moc Could you add a summary of what's included in this pull request in the PR description.

**Comment by danmcp** [comment]
@awalkaradi95moc Also please squash the commits.

**Comment by awalkaradi95moc** [comment]
This pull request is an extension to the working pull request of mount-dir pfioh (#12 ). The additions are specifically for working with swift backend. We have removed the exception handling in inner functions. 

It previously used to return `File added in swift container` even when it has failed in one of the inner functions. Now if it fails, the exception is not caught but thrown so as to return the error to the user.

**Comment by danmcp** [comment]
@awalkaradi95moc @ravisantoshgudimetla Is this ready to be merged at this point?

**Comment by awalkaradi95moc** [comment]
@danmcp Yes. We tested it through pfcon and also ran the unit tests on it. We will do the integration testing once we fix the pman job status issue.

**Pull request merged**
